telegram.bot.token=7779195144:AAHUU92ntTzQDRp_2QHY170UqRYYti-pHVY
telegram.bot.username=testikbotik
telegram.webapp.url=miniapp-lexik.amvera.io
telegram.channel.url=https://t.me/eskintouch_lab
telegram.channel.id=@orderbota
spring.datasource.url=jdbc:postgresql://loyalty-lexik.db-msk0.amvera.tech:5432/Loyalty?sslmode=prefer
spring.datasource.username=lex
spring.datasource.password=123
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
server.port=5431